version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0.0

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: flake8
      - run: pytest
  build-docker-image:
    docker:
      - image: "cimg/python:3.9.1"
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Send Image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t $DOCKER_USER/orange_county_lettings:latest .
            docker tag $DOCKER_USER/orange_county_lettings:latest $DOCKER_USER/orange_county_lettings:$CIRCLE_SHA1
            docker push $DOCKER_USER/orange_county_lettings:$CIRCLE_SHA1
            docker push $DOCKER_USER/orange_county_lettings:latest

  deploy-on-heroku:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - heroku/install
      - run: heroku container:login
      - run:
          name: Push Docker image to registry
          command: |
            docker tag $DOCKER_USER/orange_county_lettings:latest registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - heroku/release-docker-image:
          process-types: web

workflows:
  main:
    jobs:
      - run-tests
      - build-docker-image:
          requires:
            - run-tests
          filters:
            branches:
              only: master
      - publish-on-docker-hub:
          requires:
            - build-docker-image
          filters:
            branches:
              only: master
      - deploy-on-heroku:
          requires:
            - build-docker-image
          filters:
            branches:
              only: master